---
title: "COVID pm 2.5 playground"
output:
  html_document:
    df_print: paged
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Set up working environment and defaults --------------------------------------
library(envimaR)
library(htmlTable)
root_folder = path.expand("~/project/cov/CovidAirPolution/")
source(file.path(root_folder, "src/functions/000_setup.R"))
source(file.path(root_folder, "src/functions/parseHeaderWAQI.R"))
source(file.path(root_folder, "src/functions/makeSFPoints.R"))
source(file.path(root_folder, "src/functions/getCovidIT.R"))

# Air quality data -------------------------------------------------------------
#flist = Sys.glob(file.path(envrmt$`path_report-data-platform-16229-259611-lombardy`,"*.csv"))
flist = list.files(
  file.path(envrmt$`path_report-data-platform-16229-259611-lombardy`), 
  pattern = "^.*\\.csv$", full.names = TRUE)

# get data tables
pm_waqi<- sfWAQI(flist)

# make corresponding points
waqi_pts<- makeSFPoints(flist)

# get corresponinding names
statname <- getWAQINames(flist)

# create mapview data
pm25<-lapply(aq, function(x) x[,1:4])
for (i in 1:length(pm25))names(pm25[[i]])<-c("date","pm25","pm25min","pm25max")
pop = lapply(pm25, htmlTable)


# Covid-19 ---------------------------------------------------------------------
cov_it = getCovidIT()
```


Die Abbildung zeigt die räumliche Verteilung der Stationen und die verwendeten pm25 Datentabellen für die Fallstudie Italien.
```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10}
mapview(waqi_pts, popup = pop,legend = FALSE, ncol="pm25max")
```

Die Abbildung zeigt die zeitliche Entwicklung der PM 2.5 an drei Stationen sowie die neuen Fälle in der Region Lombardei.
```{r echo=FALSE, fig.width=10, message=FALSE, warning=FALSE}
# ggplot() + 
#   geom_line(data = cmb, aes(x = date, y = pm25, colour = stat)) + 
#   geom_line(data = cov_lombardia, aes(x = data, y = nuovi_positivi/10)) + 
#   scale_y_continuous(sec.axis = sec_axis(~.*10, name = "New cases")) +
#   geom_line(data = cov_Bergamo, aes(x = data, y = new_cases/10, colour = "Covid Bergamo")) + 
#   scale_y_continuous(sec.axis = sec_axis(~.*10, name = "New cases")) +
#   geom_line(data = cov_Milano, aes(x = data, y = new_cases/10, colour = "Covid Milano")) + 
#   scale_y_continuous(sec.axis = sec_axis(~.*10, name = "New cases"))

# fig = plot_ly() 
# for(l in seq_along(aq)){
#   
#   fig = fig %>% add_trace(data = aq[[l]][[1]], x = ~date, y = ~pm25, type = 'scatter', name = paste("pm 2.5", names(aq[1])), mode = 'lines+markers')
#   
# }

fig = plot_ly() 


fig = fig %>% add_trace(data = cov_admin3[cov_admin3$denominazione_provincia == "Bergamo",], x = ~data, y = ~new_cases, yaxis = "y2", name = "New cases Bergamo", line=list(color ="red", width = 5, dash = 'dot') ,mode = 'lines+markers')

fig = fig %>% add_trace(data = cov_admin3[cov_admin3$denominazione_provincia == "Milano",], x = ~data, y = ~new_cases, yaxis = "y2", name = "New cases Milano", line = list(color = 'rgb(205, 12, 24)', width = 4, dash = 'dot'),mode = 'lines+markers')

fig = fig %>% layout(yaxis2 = list(overlaying = "y", side = "right", title = "new cases"))
fig

fig = plot_ly() 
for(l in seq_along(pm25)){
  
  fig = fig %>% add_trace(data = pm25[[l]], x = ~date, y = ~pm25, type = 'scatter', name = paste("pm 2.5",waqnames[l]), mode = 'lines+markers')
  
}

fig = fig %>% add_trace(data = cov_admin3[cov_admin3$denominazione_provincia == "Bergamo",], x = ~data, y = ~new_cases, yaxis = "y2", name = "New cases Bergamo", line=list(color ="red", width = 5, dash = 'dot') ,mode = 'lines+markers')

fig = fig %>% add_trace(data = cov_admin3[cov_admin3$denominazione_provincia == "Milano",], x = ~data, y = ~new_cases, yaxis = "y2", name = "New cases Milano", line = list(color = 'rgb(205, 12, 24)', width = 4, dash = 'dot'),mode = 'lines+markers')

fig = fig %>% layout(yaxis2 = list(overlaying = "y", side = "right", title = "new cases"))
fig
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10}
pm_bergamo = pm_waqi[pm_waqi$statname == "Bergamo-Via-Meucci"]

cov_bergamo = cov_it$cov_admin3[cov_it$cov_admin3$denominazione_provincia == "Bergamo",]

# https://rpubs.com/ibn_abdullah/rwcoher

# https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-019-7607-2
```



```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10}

# merge data colums
bergamo<-merge(x = cov_admin3[cov_admin3$denominazione_provincia == "Bergamo",], y = pm25[[8]], by = "data",sort = T)
head(bergamo)
plot(bergamo$new_cases,type = "l")
plot(bergamo$pm25,type = "l")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10}
# convert date to factor
bergamo$data<-as.factor(as.character(bergamo$data))

# new_cases only is there a periodicy?

bergamo.w <- analyze.wavelet(bergamo, "new_cases",loess.span = 0,dt = 1, dj = 1/50,lowerPeriod = 1, upperPeriod = 28,make.pval = TRUE, n.sim = 10)

wt.image(bergamo.w, color.key = "interval", n.levels = 250,legend.params = list(lab = "wavelet power levels"),periodlab = "period (days)", timelab = "")
wt.image(bergamo.w, color.key = "interval", n.levels = 250,legend.params = list(lab = "wavelet power levels"),periodlab = "period (days)",label.time.axis = TRUE)

# - change scale 
max.power <- max(bergamo.w$Power)

wt.image(bergamo.w, color.key = "interval", n.levels = 250,legend.params = list(lab = "wavelet power levels"),periodlab = "period (days)",maximum.level = 1.001*max.power,show.date = TRUE, date.format = "%F", timelab = "")
wt.image(bergamo.w, color.key = "interval", n.levels = 250,legend.params = list(lab = "wavelet power levels",
                                                                           label.digits = 2),
           periodlab = "periods (days)", maximum.level = 1.25, 
         # Concerning item 1 above --- plot the square root of power:
         exponent = 0.5,
         # Concerning item 2 above --- time axis:
         show.date = FALSE, date.format = "%m%d", timelab = "", spec.time.axis = list(at = c(paste(2005:2014, "-01-01", sep = "")),labels = c(2005:2014)),timetcl = -0.5,  
         # draws outward ticks# Concerning item 3 above --- period axis:
         spec.period.axis = list(at = c(3, 7, 14, 21, 28)),periodtck = 1, periodtcl = NULL  )
         # draws horizontal lines)

```

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=10}

#--------------------------------------------------------------------
# cross wavelet anaklysis

bergamo.wc <- analyze.coherency(bergamo,my.pair = c("new_cases", "pm25"),
                                loess.span = 0,dt = 1, dj = 1/50,lowerPeriod = 1, upperPeriod = 28,
                                make.pval = TRUE, n.sim = 10)

max.power <- max(bergamo.wc$Power.xy)  # for plotting
#save(bergamo.wc, file = "cross_wavelet_transform_temperature_over_humidity")

#load("cross_wavelet_transform_temperature_over_humidity")
exponent <- 0.5
wc.image(bergamo.wc, n.levels = 250,
         legend.params = list(lab = "cross-wavelet power levels"),
         color.key = "interval",
         maximum.level = (1.001*max.power)^exponent, exponent = exponent,
         # time axis:
         label.time.axis = TRUE, 
         show.date = TRUE,
         spec.time.axis = list(at = paste(2020-02-01:2020-04-02, "-01-01", sep = ""),labels = 2020-02:2020-04),timetcl = -0.5, 
         # outward ticks
         # period axis:
         periodlab = "period (days)",
         spec.period.axis = list(at = c(3, 7, 14, 21, 28)),periodtck = 1, periodtcl = NULL)

```

